# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

# Using my-meta as the layer name
BBFILE_COLLECTIONS += "my-meta"
BBFILE_PATTERN_my-meta = "^${LAYERDIR}/"
# Higher than isar's 5
BBFILE_PRIORITY_my-meta = "10"

# Match the ISAR version you're using.
# NOTE: not sure why is it v0.6 and not v0.11
LAYERSERIES_COMPAT_my-meta = "v0.6"